name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        dart-sdk: stable
    - name: Get dependencies
      run: dart pub get
    - name: Build and test
      run: dart test
